<?php
    $a=[
    0=>[
        'tag'=>'input',
        'text'=>'姓  名:',
        'attr'=>[
            'type'=>'text',
            'name'=>'user'
        ]
    ],
    1=>[
        'tag'=>'input',
        'text'=>'性别',
        'attr'=>[
            'type'=>'radio',
            'name'=>'gender'
        ],
        'option'=>[
            'm'=>'男',
            'w'=>'女'
        ]
    ],
    2=>[
        'tag'=>'input',
        'text'=>'爱好',
        'attr'=>[
            'type'=>'checkbox',
            'name'=>'hobby[]'
        ],
        'option'=>[
            'swimming'=>'游泳',
            'reading'=>'读书',
            'running'=>'跑步'
        ],
        'default'=>[
            'swimming',
            'reading'
        ]
    ],
    3=>[
        'tag'=>'input',
        'text'=>'住址',
        'attr'=>[
            'name'=>'area',
        ],
        'option'=>[
            ''=>'---请选择---',
            'BJ'=>'北京',
            'SH'=>'上海',
            'SZ'=>'深圳'
        ]
    ],
    4=>[
        'tag'=>'input',
        'text'=>'自我介绍',
        'attr'=>[
            'name'=>'introduce',
            'cols'=>50,
            'row'=>5
        ]
    ]
];
var_dump($a);
